const images = {
    banner: '../../img/banner.png',
    logo: '../../img/logo.png',
    traveltypes: '../../img/travel_types.png',
    cities: {
        apia: '../../img/cities/apia.jpg',
        athens: '../../img/cities/athens.jpg',
        cairo: '../../img/cities/cairo.jpg',
        capetown: '../../img/cities/cape_town.jpg',
        casablanca: '../../img/cities/casablanca.jpg',
        dubai: '../../img/cities/dubai.jpg',
        istanbul: '../../img/cities/istanbul.jpg',
        lagos: '../../img/cities/lagos.jpg',
        lima: '../../img/cities/lima.jpg',
        london: '../../img/cities/london.jpg',
        newyork: '../../img/cities/new_york.jpg',
        paris: '../../img/cities/paris.jpg',
        rio: '../../img/cities/rio.jpg',
        rome: '../../img/cities/rome.jpg',
        shanghai: '../../img/cities/shanghai.jpg',
        suva: '../../img/cities/suva.jpg',
        sydney: '../../img/cities/sydney.jpg',
        tokyo: '../../img/cities/tokyo.jpg',
        toronto: '../../img/cities/toronto.jpg',
        wellington: '../../img/cities/wellington.jpg',
    },
    continents: {
        africa: '../../img/continents/africa.jpg',
        america: '../../img/continents/america.jpg',
        asia: '../../img/continents/asia.jpg',
        europe: '../../img/continents/europe.jpg',
        oceania: '../../img/continents/oceania.jpg',
    },
    flags: {
        australia: '../../img/flags/australia.png',
        brazil: '../../img/flags/brazil.png',
        canada: '../../img/flags/canada.png',
        china: '../../img/flags/china.png',
        egypt: '../../img/flags/egypt.png',
        england: '../../img/flags/england.png',
        fiji: '../../img/flags/fiji.png',
        france: '../../img/flags/france.png',
        greece: '../../img/flags/greece.png',
        italy: '../../img/flags/italy.png',
        japan: '../../img/flags/japan.png',
        morocco: '../../img/flags/morocco.png',
        newzeland: '../../img/flags/new_zealand.png',
        nigeria: '../../img/flags/nigeria.png',
        peru: '../../img/flags/peru.png',
        samoa: '../../img/flags/samoa.png',
        southafrica: '../../img/flags/south_africa.png',
        turkey: '../../img/flags/turkey.png',
        uae: '../../img/flags/uae.png',
        usa: '../../img/flags/usa.png'
    }
}

export default images;
